LuckyPaw/LuckyPaw/Models/CartItemModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LuckyPaw.Models
{
    // Cart Item Model to store bought puppies or trianing service
    public class CartItemModel
    {
        // Primary Key
        [Key]
        public int CartId { get; set; }

        // Foreign Key from pricing puppy model
        [ForeignKey("PricingPuppyModel")]
        public int PricePuppyID { get; set; }

        public string PricePuppyDesc { get; set; }

        public double PricePuppy { get; set; }

        // Foreign key from training services price model
        [ForeignKey("TrainingServicesPriceModel")]
        public int TrainingServicesPriceID { get; set; }

        public string TrainingName { get; set; }

        public double PriceTraining { get; set; }

        public int CartQty { get; set; }

        public string Email { get; set; }

    }
}

LuckyPaw/LuckyPaw/Controllers/PricingPuppyModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuckyPaw.Data;
using LuckyPaw.Models;

namespace LuckyPaw.Controllers
{
    public class PricingPuppyModelsController : Controller
    {
        private readonly LuckyPawContext _context;

        public PricingPuppyModelsController(LuckyPawContext context)
        {
            _context = context;
        }

        // GET: PricingPuppyModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.PricingPuppyModel.ToListAsync());
        }

        // GET: PricingPuppyModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pricingPuppyModel = await _context.PricingPuppyModel
                .FirstOrDefaultAsync(m => m.PricePuppyID == id);
            if (pricingPuppyModel == null)
            {
                return NotFound();
            }

            return View(pricingPuppyModel);
        }

        // GET: PricingPuppyModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PricingPuppyModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PricePuppyID,PricePuppyDesc,PricePuppy,PricePuppyImageUrl,PuppyQty")] PricingPuppyModel pricingPuppyModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pricingPuppyModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pricingPuppyModel);
        }

        // GET: PricingPuppyModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pricingPuppyModel = await _context.PricingPuppyModel.FindAsync(id);
            if (pricingPuppyModel == null)
            {
                return NotFound();
            }
            return View(pricingPuppyModel);
        }

        // POST: PricingModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PricePuppyID,PricePuppyDesc,PricePuppy,PricePuppyImageUrl,PuppyQty")] PricingPuppyModel pricingPuppyModel)
        {
            if (id != pricingPuppyModel.PricePuppyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pricingPuppyModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PricingModelExists(pricingPuppyModel.PricePuppyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pricingPuppyModel);
        }

        // GET: PricingModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pricingPuppyModel = await _context.PricingPuppyModel
                .FirstOrDefaultAsync(m => m.PricePuppyID == id);
            if (pricingPuppyModel == null)
            {
                return NotFound();
            }

            return View(pricingPuppyModel);
        }

        // POST: PricingModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pricingPuppyModel = await _context.PricingPuppyModel.FindAsync(id);
            _context.PricingPuppyModel.Remove(pricingPuppyModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PricingModelExists(int id)
        {
            return _context.PricingPuppyModel.Any(e => e.PricePuppyID == id);
        }
    }
}

LuckyPaw/LuckyPaw/Controllers/TrainingServicesPriceModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuckyPaw.Data;
using LuckyPaw.Models;

namespace LuckyPaw.Controllers
{
    public class TrainingServicesPriceModelsController : Controller
    {
        private readonly LuckyPawContext _context;

        public TrainingServicesPriceModelsController(LuckyPawContext context)
        {
            _context = context;
        }

        // GET: TrainingServicesPriceModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.TrainingServicesPriceModel.ToListAsync());
        }

        // GET: TrainingServicesPriceModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainingServicesPriceModel = await _context.TrainingServicesPriceModel
                .FirstOrDefaultAsync(m => m.TrainingServicesPriceID == id);
            if (trainingServicesPriceModel == null)
            {
                return NotFound();
            }

            return View(trainingServicesPriceModel);
        }

        // GET: TrainingServicesPriceModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TrainingServicesPriceModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrainingServicesPriceID,TrainingName,PriceTraining,TrainingDesc")] TrainingServicesPriceModel trainingServicesPriceModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainingServicesPriceModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trainingServicesPriceModel);
        }

        // GET: TrainingServicesPriceModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainingServicesPriceModel = await _context.TrainingServicesPriceModel.FindAsync(id);
            if (trainingServicesPriceModel == null)
            {
                return NotFound();
            }
            return View(trainingServicesPriceModel);
        }

        // POST: TrainingServicesPriceModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrainingServicesPriceID,TrainingName,PriceTraining,TrainingDesc")] TrainingServicesPriceModel trainingServicesPriceModel)
        {
            if (id != trainingServicesPriceModel.TrainingServicesPriceID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainingServicesPriceModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainingServicesPriceModelExists(trainingServicesPriceModel.TrainingServicesPriceID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainingServicesPriceModel);
        }

        // GET: TrainingServicesPriceModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainingServicesPriceModel = await _context.TrainingServicesPriceModel
                .FirstOrDefaultAsync(m => m.TrainingServicesPriceID == id);
            if (trainingServicesPriceModel == null)
            {
                return NotFound();
            }

            return View(trainingServicesPriceModel);
        }

        // POST: TrainingServicesPriceModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trainingServicesPriceModel = await _context.TrainingServicesPriceModel.FindAsync(id);
            _context.TrainingServicesPriceModel.Remove(trainingServicesPriceModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainingServicesPriceModelExists(int id)
        {
            return _context.TrainingServicesPriceModel.Any(e => e.TrainingServicesPriceID == id);
        }
    }
}

LuckyPaw/LuckyPaw/Views/CartItemModels/CartItemsView.cshtml
@model IEnumerable<LuckyPaw.Models.CartItemModel>

@{
    ViewData["Title"] = "CartItemsView";
}

<h1>Shopping Items Bought</h1>
<h2>Puppies</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PricePuppyDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePuppy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartQty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <!--If code from https://www.w3schools.com/asp/razor_cs_logic.asp-->
            @if (item.TrainingServicesPriceID == -1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PricePuppyDesc)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.PricePuppy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CartQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<h2>Training Services</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TrainingName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceTraining)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartQty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <!--If code from https://www.w3schools.com/asp/razor_cs_logic.asp-->
            @if (item.PricePuppyID == -1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrainingName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PriceTraining)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CartQty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

LuckyPaw/LuckyPaw/Views/CartItemModels/CheckOut.cshtml
@model IEnumerable<LuckyPaw.Models.CartItemModel>

@{
    ViewData["Title"] = "CheckOut";
}

<h1>CheckOut Items</h1>
<p>Please prepare the check or money order when you drop off or pickup your puppies</p>
<h2>Puppies</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PricePuppyDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePuppy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartQty)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.TrainingServicesPriceID == -1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PricePuppyDesc)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.PricePuppy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CartQty)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<p>
    Total Puppy Cost: $ @ViewData["puppyTotal"]
</p>

<h2>Training Services</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TrainingName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceTraining)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartQty)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.PricePuppyID == -1)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrainingName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PriceTraining)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CartQty)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<p>
    Total Training Services: $ @ViewData["trainingServicesTotal"]
</p>

LuckyPaw/LuckyPaw/Views/CartItemModels/Create.cshtml
@model LuckyPaw.Models.CartItemModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CartItemModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PricePuppyID" class="control-label"></label>
                <input asp-for="PricePuppyID" class="form-control" />
                <span asp-validation-for="PricePuppyID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainingServicesPriceID" class="control-label"></label>
                <input asp-for="TrainingServicesPriceID" class="form-control" />
                <span asp-validation-for="TrainingServicesPriceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CartQty" class="control-label"></label>
                <input asp-for="CartQty" class="form-control" />
                <span asp-validation-for="CartQty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LuckyPaw/LuckyPaw/Views/CartItemModels/Delete.cshtml
@model LuckyPaw.Models.CartItemModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CartItemModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PricePuppyID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PricePuppyID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TrainingServicesPriceID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TrainingServicesPriceID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CartQty)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CartQty)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CartId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LuckyPaw/LuckyPaw/Views/CartItemModels/Details.cshtml
@model LuckyPaw.Models.CartItemModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CartItemModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PricePuppyID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PricePuppyID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TrainingServicesPriceID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TrainingServicesPriceID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CartQty)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CartQty)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CartId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LuckyPaw/LuckyPaw/Views/CartItemModels/Edit.cshtml
@model LuckyPaw.Models.CartItemModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CartItemModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CartId" />
            <div class="form-group">
                <label asp-for="PricePuppyID" class="control-label"></label>
                <input asp-for="PricePuppyID" class="form-control" />
                <span asp-validation-for="PricePuppyID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrainingServicesPriceID" class="control-label"></label>
                <input asp-for="TrainingServicesPriceID" class="form-control" />
                <span asp-validation-for="TrainingServicesPriceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CartQty" class="control-label"></label>
                <input asp-for="CartQty" class="form-control" />
                <span asp-validation-for="CartQty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LuckyPaw/LuckyPaw/Views/CartItemModels/Index.cshtml
@model IEnumerable<LuckyPaw.Models.CartItemModel>

@{
    ViewData["Title"] = "Index";

    var count = 0;
}

<h1>Shopping Cart Items</h1>
<h2>Puppies</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PricePuppyDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePuppy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartQty)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <!--If and variable code from https://www.w3schools.com/asp/razor_cs_logic.asp-->
            <!--A puppy has a training services price id of -1, so we check for that and display the puppy information-->
            @if (item.TrainingServicesPriceID == -1)
            {
                count++;
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PricePuppyDesc)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.PricePuppy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CartQty)
                    </td>
                    <td>
                        <a asp-action="RemovePuppy" asp-route-id="@item.PricePuppyID">Remove Puppy</a>
                        <!--
                    <a asp-action="Edit" asp-route-id="@item.CartId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.CartId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.CartId">Delete</a>-->
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<p>
    <a asp-controller="PricingPuppyModels" asp-action="Index">Continue Shopping for Puppies</a>
</p>

<h2>Training Services</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TrainingName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceTraining)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartQty)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <!--If and variable code from https://www.w3schools.com/asp/razor_cs_logic.asp-->
            <!--A training service has a puppy id of -1, so we check for that and display the training services information-->
            @if (item.PricePuppyID == -1)
            {
                count++;
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrainingName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PriceTraining)
                    </td>
                    <td>
                        <!--Text box code from https://www.tutorialsteacher.com/mvc/htmlhelper-textbox-textboxfor -->
                        @Html.TextBox("cartQty", @item.CartQty, null)
                        <a asp-action="AddOneToTrainingServicesCart" asp-route-id="@item.TrainingServicesPriceID">Add one |</a>
                        <a asp-action="RemoveOneFromTrainingServicesCart" asp-route-id="@item.TrainingServicesPriceID">Remove one |</a>
                        <!--@Html.DisplayFor(modelItem => item.CartQty)-->
                        <a asp-action="RemoveTrainingService" asp-route-id="@item.TrainingServicesPriceID">Remove Training Service</a>
                    </td>
                    <td>
                        <!--<a asp-action="Edit" asp-route-id="@item.CartId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.CartId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.CartId">Delete</a>-->
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<p>
    <a asp-controller="TrainingServicesPriceModels" asp-action="Index">Continue Shopping for Training Services</a>
</p>

@if (count > 0) {
<p>
    <a asp-action="CheckOut">CheckOut</a>
</p>
}