LuckyPaw/LuckyPaw/Controllers/CartItemModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuckyPaw.Data;
using LuckyPaw.Models;
using LuckyPaw.Helpers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace LuckyPaw.Controllers
{
    public class CartItemModelsController : Controller
    {
        private readonly LuckyPawContext _context;

        public CartItemModelsController(LuckyPawContext context)
        {
            _context = context;
        }

        // GET: CartItemModels
        public async Task<IActionResult> Index()
        {
            // Code below copied from http://learningprogramming.net/net/asp-net-core-mvc/build-shopping-cart-with-session-in-asp-net-core-mvc/
            // and updated

            // Get the puppyCart and training services cart
            var puppyCart = SessionHelper.GetObjectFromJson<List<CartItemModel>>(HttpContext.Session, "puppyCart");
            var trainingServicesCart = SessionHelper.GetObjectFromJson<List<CartItemModel>>(HttpContext.Session, "trainingServicesCart");

            // If the puppy cart is not null and the training services cart is not null, add the training services cart to 
            // the puppy cart
            if(puppyCart != null && trainingServicesCart != null)
                puppyCart.AddRange(trainingServicesCart);
            
            // If the puppy cart is not null, return the puppy cart to the view
            if (puppyCart != null)
                return View(puppyCart);
            // If the training services cart is not null, return the training services cart to the view
            else if (trainingServicesCart != null)
                return View(trainingServicesCart);
            // Else create a tempCartList to make sure the view model is not null, otherwise it would throw
            // an object reference not set to an object
            else
            {
                List<CartItemModel> tempCartList = new List<CartItemModel>();
                CartItemModel tempCart = new CartItemModel { PricePuppyID = 0, PricePuppyDesc = "", PricePuppy = 0, TrainingServicesPriceID = 0,
                    TrainingName = "", PriceTraining = 0, CartQty = 0, Email = "" };

                tempCartList.Add(tempCart);

                return View(tempCartList);
            }
        }

        // GET: AddOneToTrainingServicesCart
        public async Task<IActionResult> AddOneToTrainingServicesCart(int? id)
        {
            // Code below copied from http://learningprogramming.net/net/asp-net-core-mvc/build-shopping-cart-with-session-in-asp-net-core-mvc/
            // and updated it.

            // Get the training services cart
            List<CartItemModel> cart = SessionHelper.GetObjectFromJson<List<CartItemModel>>(HttpContext.Session, "trainingServicesCart");

            // Check to see if the training service that was selected is in the training services cart
            int index = isExistTrainingService((int)id);

            // If the index is not equal -1
            if (index != -1)
            {
                // Update the training services cart cartQty
                cart[index].CartQty++;

                // Get the cartItemModel where the training services price id is equal to the selected training service id
                var cartItemModel = await _context.CartItemModel
                .FirstOrDefaultAsync(m => m.TrainingServicesPriceID == id);

                // Check to see if the cart item model is null
                if (cartItemModel == null)
                {
                    return NotFound();
                }

                // Update the cart item model cart quantity
                cartItemModel.CartQty++;

                // If the modelState is valid, update the cart item in the database
                //detail of model state
                //https://stackoverflow.com/questions/881281/what-is-modelstate-isvalid-valid-for-in-asp-net-mvc-in-nerddinner#targetText=ModelState.IsValid%20tells%20you%20if,validation%20system%20you're%20using.

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(cartItemModel);    // Will update the cart table
                        await _context.SaveChangesAsync(); // Save the changes
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        // If any errors, throw an exception
                        throw;
                    }
                }
            }

            SessionHelper.SetObjectAsJson(HttpContext.Session, "trainingServicesCart", cart);

            return RedirectToAction("Index");
        }

        // GET: RemoveOneFromTrainingServicesCart
        public async Task<IActionResult> RemoveOneFromTrainingServicesCart(int? id)
        {
            // Code below copied from http://learningprogramming.net/net/asp-net-core-mvc/build-shopping-cart-with-session-in-asp-net-core-mvc/
            // and updated it.

            // Get the training services cart
            List<CartItemModel> cart = SessionHelper.GetObjectFromJson<List<CartItemModel>>(HttpContext.Session, "trainingServicesCart");

            // Check to see if the training service that was selected is in the training services cart
            int index = isExistTrainingService((int)id);

            // If the index is not equal -1
            if (index != -1)
            {
                // If the training services cart for the selected training service cart quantity is 1
                if (cart[index].CartQty == 1)
                {
                    // Remove the selected training services cart item from the training services cart
                    cart.RemoveAt(index);

                    // Get the cart item for the selected training service from the training services cart
                    var cartItemModel = await _context.CartItemModel
                    .FirstOrDefaultAsync(m => m.TrainingServicesPriceID == id);

                    // If the cart item model is null, return not found
                    if (cartItemModel == null)
                    {
                        return NotFound();
                    }

                    // Remove the cart item for the selected training service from the database and save the changes
                    _context.CartItemModel.Remove(cartItemModel);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    // Else decrement the training 
                    cart[index].CartQty--;

                    var cartItemModel = await _context.CartItemModel
                    .FirstOrDefaultAsync(m => m.TrainingServicesPriceID == id);

                    if (cartItemModel == null)
                    {
                        return NotFound();
                    }

                    cartItemModel.CartQty--;

                    if (ModelState.IsValid)
                    {
                        try
                        {
                            _context.Update(cartItemModel);
                            await _context.SaveChangesAsync();
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            throw;
                        }
                    }
                }
            }
            
            // Update the training services cart to reflect the changes made above to the cart
            SessionHelper.SetObjectAsJson(HttpContext.Session, "trainingServicesCart", cart);

            return RedirectToAction("Index");
        }

        // GET: BuyPuppy, Authorize code from https://www.red-gate.com/simple-talk/dotnet/asp-net/thoughts-on-asp-net-mvc-authorization-and-security/
        // Authorize attribute to redirect the user to the login page if they have not logged in
        [Authorize]
        public async Task<IActionResult> BuyPuppy(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Code below copied from http://learningprogramming.net/net/asp-net-core-mvc/build-shopping-cart-with-session-in-asp-net-core-mvc/
            // and updated it.

            // Get the puppy from the PricePuppy table
            var pricingPuppyModel = await _context.PricingPuppyModel.FindAsync(id);

            if (pricingPuppyModel == null)
            {
                return NotFound();
            }

            // Check if the puppy cart has been created or not .i.e is it null 
            if (SessionHelper.GetObjectFromJson<List<CartItemModel>>(HttpContext.Session, "puppyCart") == null)
            {
                //Create the cart
                List<CartItemModel> cart = new List<CartItemModel>();

                //Creating cart item model object
                CartItemModel newCartItem = new CartItemModel { PricePuppyID = pricingPuppyModel.PricePuppyID, PricePuppyDesc = pricingPuppyModel.PricePuppyDesc,
                    PricePuppy = pricingPuppyModel.PricePuppy, TrainingServicesPriceID = -1,
                    TrainingName = "", PriceTraining = 0, CartQty = 1, Email = User.Identity.Name };

                cart.Add(newCartItem);

                if (ModelState.IsValid)
                {
                    _context.Add(newCartItem);
                    await _context.SaveChangesAsync();
                }

                SessionHelper.SetObjectAsJson(HttpContext.Session, "puppyCart", cart);
            }
            else
            {
                //The cart has been created
                List<CartItemModel> cart = SessionHelper.GetObjectFromJson<List<CartItemModel>>(HttpContext.Session, "puppyCart");

LuckyPaw/LuckyPaw/Controllers/TrainersModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LuckyPaw.Data;
using LuckyPaw.Models;

namespace LuckyPaw.Controllers
{
    public class TrainersModelsController : Controller
    {
        private readonly LuckyPawContext _context;

        public TrainersModelsController(LuckyPawContext context)
        {
            _context = context;
        }

        // GET: TrainersModels
        public async Task<IActionResult> Index()
        {
            // Get the trainers
            var trainersModel = await _context.TrainersModel.ToListAsync();

            // Create an updatedTrainersModel array
            var updatedTrainersModel = new TrainersModel[trainersModel.Count];

            int i = 0;

            // For each trainer in trainersModel
            foreach (TrainersModel trainer in trainersModel)
            {
                // Get all the dogs that have been trained by trainer.TrainerId
                var trainingDogCount = await _context.TrainingDogModel.CountAsync(m => m.TrainerId == trainer.TrainerId);

                // Set the training dog count to the trainer dog number
                trainer.DogNumber = trainingDogCount;

                // Set the updated trainer to the updatedTrainersModel
                updatedTrainersModel[i] = trainer;

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(trainer);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                       
                        throw;
                       
                    }
                }

                i++;
            }

            return View(updatedTrainersModel);
        }

        // GET: TrainersModels/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainersModel = await _context.TrainersModel
                .FirstOrDefaultAsync(m => m.TrainerId == id);
            if (trainersModel == null)
            {
                return NotFound();
            }

            return View(trainersModel);
        }

        // GET: TrainersModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TrainersModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrainerId,TrainerName,TrainerArea,DogNumber")] TrainersModel trainersModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainersModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trainersModel);
        }

        // GET: TrainersModels/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainersModel = await _context.TrainersModel.FindAsync(id);
            if (trainersModel == null)
            {
                return NotFound();
            }
            return View(trainersModel);
        }

        // POST: TrainersModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("TrainerId,TrainerName,TrainerArea,DogNumber")] TrainersModel trainersModel)
        {
            if (id != trainersModel.TrainerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainersModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainersModelExists(trainersModel.TrainerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainersModel);
        }

        // GET: TrainersModels/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainersModel = await _context.TrainersModel
                .FirstOrDefaultAsync(m => m.TrainerId == id);
            if (trainersModel == null)
            {
                return NotFound();
            }

            return View(trainersModel);
        }

        // POST: TrainersModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var trainersModel = await _context.TrainersModel.FindAsync(id);
            _context.TrainersModel.Remove(trainersModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainersModelExists(string id)
        {
            return _context.TrainersModel.Any(e => e.TrainerId == id);
        }
    }
}

LuckyPaw/LuckyPaw/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LuckyPaw</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LuckyPaw</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TrainersModels" asp-action="Index">Trainers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TrainingDogModels" asp-action="Index">Trained Dog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TrainingServicesPriceModels" asp-action="Index">Training Services Price</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PricingPuppyModels" asp-action="Index">Puppy For Sale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-info btnShoppingCart" asp-area="" asp-controller="CartItemModels" asp-action="Index">Shopping Cart</a>
                        </li>
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <table cellpadding="10">
                <tr>
                    <td>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                            {
                                
                               <a class="nav-link text-dark btn btn-info btnCartItemsView" asp-area="" asp-controller="CartItemModels" asp-action="CartItemsView">Bought Items</a>
                                    
                            }
                        }
                    </td>
                    <td>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                
                              <a class="nav-link text-dark btn btn-info btnManageAccounts" asp-area="" asp-controller="Home" asp-action="ManageAccounts">Accounts</a>
                                   
                            }
                        }
                    </td>
                </tr>
            </table>
        </div>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - LuckyPaw - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>